spring.application.name=Notes_Manager_Backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/notes_db
spring.datasource.username=postgres
spring.datasource.password=26081106
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080

server.ssl.enabled=true

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=26081106
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=springboot
